# Generated by Django 6.0.6 on 2026-07-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
