# Generated by Django 6.0.6 on 2026-07-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_reminder_calendar_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('SCHEDULE_EMAIL', 'Schedule an Email'), ('REMIND_ME', 'Remind Me')], default='SCHEDULE_EMAIL', max_length=20),
        ),
    ]
