# Generated by Django 6.0.6 on 2026-07-08 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
        ('reminders', '0003_reminder_reminder_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='recipient',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('SCHEDULE_EMAIL', 'Schedule an Email'), ('REMIND_ME', 'Remind Me'), ('MEETING', 'Meeting')], default='SCHEDULE_EMAIL', max_length=20),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('NEEDS_CONFIRMATION', 'Needs Confirmation'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='reminder',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AI_DETECTED', 'AI Detected')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='reminder',
            name='ai_confidence',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='reminder',
            name='source_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_reminders', to='emails.emailmetadata'),
        ),
    ]