# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_automation_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trash_retention_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]