# Generated by Django 6.0.6 on 2026-06-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(max_length=255, unique=True)),
                ('thread_id', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('sender', models.EmailField(max_length=254)),
                ('receiver', models.EmailField(max_length=254)),
                ('snippet', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('priority', models.CharField(blank=True, max_length=20)),
                ('starred', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
