# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmetadata',
            name='ai_processed',
            field=models.BooleanField(default=False),
        ),
    ]
