# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_emailmetadata_ai_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmetadata',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailmetadata',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]