# Generated by Django 6.0.6 on 2026-07-01 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emails', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=30)),
                ('priority', models.CharField(blank=True, max_length=20)),
                ('importance', models.CharField(blank=True, max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('suggested_action', models.CharField(blank=True, max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('generated_reply', models.TextField(blank=True)),
                ('extracted_tasks', models.JSONField(blank=True, default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='emails.emailmetadata')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
