# Generated by Django 6.0.6

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_emailmetadata_ai_processed'),
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('auto_replied', 'Auto-replied'), ('draft_created', 'Draft created'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('priority', models.CharField(blank=True, max_length=20)),
                ('importance', models.CharField(blank=True, max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('reply_content', models.TextField(blank=True)),
                ('reasoning', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='emails.emailmetadata')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
