# Generated by Django 6.0.6 on 2026-07-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_emailactionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailactionlog',
            name='action',
            field=models.CharField(choices=[('auto_replied', 'Auto-replied'), ('draft_created', 'Draft created'), ('skipped', 'Skipped'), ('failed', 'Failed'), ('meeting_scheduled', 'Meeting scheduled'), ('meeting_needs_confirmation', 'Meeting needs confirmation')], max_length=30),
        ),
    ]