# Generated by Django 6.0.6 on 2026-07-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_emailactionlog_meeting_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='detected_language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='translated_body',
            field=models.TextField(blank=True),
        ),
    ]
